name: mtg_log_finder
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: daisuke <email@example.com>

environment:
  sdk: '2.0.0-dev.67.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  sass_builder: ^2.0.0
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: '>=0.3.6 <0.5.0'
  chrome: any
  googleapis: any
  googleapis_auth: any
  google_oauth2_client: any
  intl: any
  dart_config: any
  sass: ^1.9.0
